package ace.domain;

public enum PacketType {
	LOGIN, CREATEUSER, MESSAGESALL, FAILURE, DISCONNECT, ONLINE, OFFLINE, CREATCHEATROOM, ADDTOCHEATROOM, DELETECHEATROOM, LEAVEROOM, START, MOVE, MESSAGESROOM
}
